// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using shirtPactice.Data;

#nullable disable

namespace shirtPactice.Migrations
{
    [DbContext(typeof(ShirtDbContext))]
    partial class ShirtDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("shirtPactice.Modal.Shirt", b =>
                {
                    b.Property<int>("shirtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("shirtId"));

                    b.Property<string>("gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("shirtDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("shirtModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("shirtName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("size")
                        .HasColumnType("int");

                    b.HasKey("shirtId");

                    b.ToTable("Shirts");

                    b.HasData(
                        new
                        {
                            shirtId = 1,
                            gender = "Male",
                            shirtDescription = "A casual t-shirt",
                            shirtModel = "Model A",
                            shirtName = "T-Shirt",
                            size = 42
                        },
                        new
                        {
                            shirtId = 2,
                            gender = "Female",
                            shirtDescription = "A formal polo shirt",
                            shirtModel = "Model B",
                            shirtName = "Polo Shirt",
                            size = 38
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
